# Generated by Django 3.0.5 on 2020-04-08 20:38

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('status', '0003_auto_20200406_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
