# Generated by Django 3.0.5 on 2020-04-17 21:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('status', '0004_auto_20200408_1638'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DomainList',
            new_name='EmailDomainList',
        ),
        migrations.AlterModelOptions(
            name='emaildomainlist',
            options={'verbose_name': 'Email Domain', 'verbose_name_plural': 'Email Domains'},
        ),
        migrations.RenameField(
            model_name='emaildomainlist',
            old_name='domain_description',
            new_name='email_domain_description',
        ),
        migrations.RenameField(
            model_name='emaildomainlist',
            old_name='domain_name',
            new_name='email_domain_name',
        ),
        migrations.AlterField(
            model_name='service',
            name='service_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='notify_action',
            field=models.BooleanField(choices=[(False, 'No'), (True, 'Yes')], default=True,
                                      verbose_name='Ticket notified'),
        ),
    ]
