# Generated by Django 3.0.5 on 2020-04-18 21:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('status', '0005_auto_20200417_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_domain_name', models.CharField(max_length=100, unique=True, verbose_name='Client Domain')),
                ('client_domain_description', models.TextField(blank=True, null=True)),
                ('services', models.ManyToManyField(to='status.Service')),
            ],
            options={
                'verbose_name': 'Client Domain',
                'verbose_name_plural': 'Client Domains',
                'ordering': ['client_domain_name'],
            },
        ),
    ]
