# Generated by Django 3.0.5 on 2020-04-18 21:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('status', '0006_clientdomain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='services',
        ),
        migrations.AddField(
            model_name='region',
            name='client_domains',
            field=models.ManyToManyField(to='status.ClientDomain'),
        ),
    ]
