# Generated by Django 3.0.5 on 2020-04-28 14:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('status', '0007_auto_20200418_1759'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticketlog',
            old_name='service_history',
            new_name='ticket',
        ),
    ]
