# Generated by Django 3.0.5 on 2020-04-28 15:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('status', '0013_auto_20200428_1106'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmailDomainList',
            new_name='EmailDomain',
        ),
    ]
