# Generated by Django 3.0.5 on 2020-04-28 15:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('status', '0014_auto_20200428_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaildomain',
            name='domain',
            field=models.CharField(max_length=100, unique=True, verbose_name='Domain Name'),
        ),
    ]
