# Generated by Django 3.0.5 on 2020-04-28 15:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('status', '0015_auto_20200428_1124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticketlog',
            old_name='event_status',
            new_name='status',
        ),
    ]
