# Generated by Django 3.0.5 on 2020-04-28 15:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('status', '0016_auto_20200428_1133'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StatusCategory',
            new_name='Status',
        ),
    ]
