# Generated by Django 3.0.5 on 2020-04-28 21:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('status', '0018_auto_20200428_1733'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='status_category_color_hex',
            new_name='color_hex',
        ),
    ]
