# Generated by Django 3.0.5 on 2020-04-28 21:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('status', '0021_auto_20200428_1745'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subservice',
            options={'ordering': ['name'], 'verbose_name': 'Sub-Service', 'verbose_name_plural': 'Sub-Services'},
        ),
        migrations.RenameField(
            model_name='subservice',
            old_name='sub_service_name',
            new_name='name',
        ),
    ]
