# Generated by Django 3.0.5 on 2020-04-28 21:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('status', '0022_auto_20200428_1752'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subservice',
            old_name='sub_service_description',
            new_name='description',
        ),
    ]
