# Generated by Django 3.0.5 on 2020-04-28 22:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('status', '0023_auto_20200428_1753'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['name'], 'verbose_name': 'Region', 'verbose_name_plural': 'Regions'},
        ),
        migrations.RenameField(
            model_name='region',
            old_name='region_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='region',
            old_name='region_name',
            new_name='name',
        ),
    ]
