# Generated by Django 3.0.5 on 2020-04-28 22:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('status', '0024_auto_20200428_1802'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientdomain',
            options={'ordering': ['name'], 'verbose_name': 'Client Domain', 'verbose_name_plural': 'Client Domains'},
        ),
        migrations.RenameField(
            model_name='clientdomain',
            old_name='client_domain_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='clientdomain',
            old_name='client_domain_name',
            new_name='name',
        ),
    ]
