# Generated by Django 3.0.5 on 2020-04-29 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0026_auto_20200428_1815'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='description',
            new_name='t_description',
        ),
    ]
