# Generated by Django 3.0.5 on 2020-04-29 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0028_auto_20200429_0932'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='priority',
            options={'ordering': ['tag'], 'verbose_name': 'Priority', 'verbose_name_plural': 'Priorities'},
        ),
        migrations.RenameField(
            model_name='priority',
            old_name='priority_color',
            new_name='color',
        ),
        migrations.RenameField(
            model_name='priority',
            old_name='priority_color_hex',
            new_name='color_hex',
        ),
        migrations.RenameField(
            model_name='priority',
            old_name='priority_tag',
            new_name='tag',
        ),
    ]
