# Generated by Django 3.0.5 on 2020-04-29 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0030_auto_20200429_0948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topology',
            name='priority',
        ),
    ]
