# Generated by Django 3.0.5 on 2020-04-29 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0031_remove_topology_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='topology',
            name='priority',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='status.Priority'),
            preserve_default=False,
        ),
    ]
