# Generated by Django 3.0.5 on 2020-04-29 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0032_topology_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topology',
            name='priority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='status.Priority'),
        ),
    ]
