# Generated by Django 3.0.5 on 2020-04-29 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0033_auto_20200429_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topology',
            name='subservices',
            field=models.ManyToManyField(to='status.SubService', verbose_name='Sub - Service'),
        ),
    ]
