# Generated by Django 3.0.5 on 2020-04-29 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0034_auto_20200429_1006'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubServiceServices',
        ),
    ]
