# Generated by Django 3.0.5 on 2020-04-29 15:03

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0035_delete_subserviceservices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdomain',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Notes'),
        ),
    ]
