# Generated by Django 3.0.5 on 2020-04-29 15:22

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0037_auto_20200429_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaildomain',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
