# Generated by Django 3.0.5 on 2020-04-29 15:31

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0038_auto_20200429_1122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emaildomain',
            old_name='description',
            new_name='domain_description',
        ),
        migrations.RemoveField(
            model_name='clientdomain',
            name='description',
        ),
        migrations.RemoveField(
            model_name='region',
            name='description',
        ),
        migrations.AddField(
            model_name='clientdomain',
            name='domain_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='region',
            name='region_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
