# Generated by Django 3.0.5 on 2020-04-29 15:37

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0039_auto_20200429_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subservice',
            name='description',
        ),
        migrations.AddField(
            model_name='subservice',
            name='subservice_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
