# Generated by Django 3.0.5 on 2020-05-01 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0040_auto_20200429_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='subservices',
            field=models.ManyToManyField(blank=True, related_name='Subscriber', to='status.SubService', verbose_name='Sub - Service'),
        ),
    ]
