# Generated by Django 3.0.5 on 2020-05-01 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0041_auto_20200501_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='subservices',
            field=models.ManyToManyField(blank=True, to='status.SubService', verbose_name='Sub - Service'),
        ),
    ]
