# Generated by Django 3.0.6 on 2020-06-23 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0043_auto_20200505_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='scope',
            field=models.CharField(blank=True, choices=[('multi_domain', 'Multi-Domain'), ('inter_domain', 'Inter-Domain')], default='multi_domain', max_length=30),
        ),
        migrations.AddField(
            model_name='ticket',
            name='client_domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='status.ClientDomain', verbose_name='Client Service'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='status.Service', verbose_name='Service'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='sub_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='status.SubService', verbose_name='Sub-Service'),
        ),
    ]
