# Generated by Django 3.0.6 on 2020-06-05 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0043_auto_20200505_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='scope',
            field=models.CharField(blank=True, choices=[('multi_domain', 'Multi-Domain'), ('inter_domain', 'Inter-Domain')], default='multi_domain', max_length=30),
        ),
    ]
