# Generated by Django 3.0.7 on 2020-06-22 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0044_service_scope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='scope',
            field=models.CharField(choices=[('multi_domain', 'Multi-Domain'), ('inter_domain', 'Inter-Domain')], default='multi_domain', max_length=30),
        ),
    ]
