# Generated by Django 3.0.6 on 2020-06-23 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0044_auto_20200623_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='client_domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='status.ClientDomain', verbose_name='Client Domain'),
        ),
    ]
