# Generated by Django 3.0.6 on 2020-07-14 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0046_auto_20200706_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='sub_services',
            field=models.ManyToManyField(blank=True, related_name='SubService', to='status.SubService', verbose_name='Sub-Services'),
        ),
    ]
