# Generated by Django 3.0.6 on 2020-06-08 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0046_auto_20200605_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdomain',
            name='inter_domain',
            field=models.BooleanField(default=False),
        ),
    ]
