# Generated by Django 3.0.6 on 2020-06-08 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0047_clientdomain_inter_domain'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientdomain',
            old_name='inter_domain',
            new_name='is_inter_domain',
        ),
    ]
