# Generated by Django 3.0.6 on 2020-06-08 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0048_auto_20200608_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientdomain',
            name='is_inter_domain',
        ),
    ]
