# Generated by Django 3.0.6 on 2020-06-09 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0049_remove_clientdomain_is_inter_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdomain',
            name='multi_domain_services',
            field=models.ManyToManyField(blank=True, related_name='multi_domain_services', to='status.Service'),
        ),
    ]
